on: [pull_request] 
 
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - id: foo
      uses: bhuvi11/Test_action@v3
      with:
        who-to-greet: 'Testing for bhuvi repository action'
    - run: echo random-number ${{ steps.foo.outputs.random-number }}
    - run: echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
      shell: bash
    - run: echo hello wednesday > math-homework.txt
    #- name: test
     # run : |
      # echo "::set-output name=action_fruit::${github.workspace}/math-homework.txt" 
     # id: run_test
    - name: get test
      run: echo ${{(steps.run_test.outputs.action_fruit)}}
    
    - uses: actions/upload-artifact@v2
      with: 
         name: homework
         path: math-homework.txt

       
    - uses: actions/download-artifact@v2
      with:
       name: homework
       
